/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import database.MyConnection;
import java.awt.Frame;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import model.Tugas;
import model.tabel.TugasTableModel;
import service.CRUD;
import widgets.MyPopup;

/**
 *
 * @author ZAFL
 */
public class TugasView extends javax.swing.JInternalFrame {

    public int selectedBaris = -1;

    Connection conn;
    DialogTugas dialogTugas = new DialogTugas((Frame) SwingUtilities.getWindowAncestor(this), this, true);
    MyPopup popupMenu = new MyPopup(this);

    CRUD crud = new CRUD();

    /**
     * Creates new form TugasView
     */
    public TugasView() {
        initComponents();

        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        ((BasicInternalFrameUI) this.getUI()).setEastPane(null);
        ((BasicInternalFrameUI) this.getUI()).setSouthPane(null);
        ((BasicInternalFrameUI) this.getUI()).setWestPane(null);
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        try {
            conn = (Connection) MyConnection.getConnection();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        popupMenu.setInvoker(tableTugas);

        initTable();
    }

    public JTable getTable() {
        return tableTugas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tableTugas = new javax.swing.JTable();
        myButton1 = new widgets.MyButton();

        setMinimumSize(new java.awt.Dimension(960, 540));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("TUGAS");

        tableTugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableTugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableTugasMouseReleased(evt);
            }
        });
        jScrollPane.setViewportView(tableTugas);

        myButton1.setText("Tambah");
        myButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        showDialog(false);
    }//GEN-LAST:event_myButton1ActionPerformed

    private void tableTugasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTugasMouseReleased
        if (evt.isPopupTrigger()) {
            JTable source = (JTable) evt.getSource();
            int row = source.rowAtPoint(evt.getPoint());
            int column = source.columnAtPoint(evt.getPoint());

            if (!source.isRowSelected(row)) {
                source.changeSelection(row, column, false, false);
            }
            popupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
            selectedBaris = tableTugas.getSelectedRow();
        }
    }//GEN-LAST:event_tableTugasMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblTitle;
    private widgets.MyButton myButton1;
    public javax.swing.JTable tableTugas;
    // End of variables declaration//GEN-END:variables

    public int getSelectedRow() {
        return tableTugas.getSelectedRow();
    }

    private void showDialog(boolean isOnEdit) {
        if (isOnEdit) {
            dialogTugas.isOnEdit = false;
        }

        dialogTugas.setLocationRelativeTo(null);
        dialogTugas.setVisible(true);
    }

    public void editDialog(boolean isonEdit) {
        int baris = selectedBaris;

    }

    public void initTable() {
        try {
            List<Tugas> semuaTugas = crud.getAllTugasWithJoin(conn);
            TugasTableModel model = new TugasTableModel(semuaTugas);
            tableTugas.setModel(model);

            int col[] = {1, 4};
            for (int i : col) {
                tableTugas.getColumnModel().getColumn(i).setMinWidth(0);
                tableTugas.getColumnModel().getColumn(i).setMaxWidth(0);
                tableTugas.getColumnModel().getColumn(i).setWidth(0);
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
            Logger.getLogger(TugasView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
